# Generated by Django 4.1.6 on 2023-03-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="city",
            field=models.CharField(default="서울", max_length=80),
        ),
        migrations.AlterField(
            model_name="perk",
            name="details",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="perk",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
