# Generated by Django 4.1.6 on 2023-03-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "experiences",
            "0004_alter_experience_category_alter_experience_host_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="perks",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="experiences", to="experiences.perk"
            ),
        ),
    ]
