# Generated by Django 4.1.6 on 2023-03-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0005_alter_experience_perks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="perks",
            field=models.ManyToManyField(
                blank=True, related_name="experiences", to="experiences.perk"
            ),
        ),
    ]
